### ISSUE TITLE
Java error while trying to run benchmarks

### ISSUE THREAD

**Issue by goxul** [encryptogroup/LLVM-for-MPC#1]
I followed the instructions and installed all the requirements as mentioned in the Readme. But when I am trying to run the benchmarks by running ```make llvm``` inside the ```Benchmarks``` folder, in particular this part of the Makefile

```
for example in biomatch_llvm dummy_llvm euclid_llvm gauss_llvm ; do \
	java $(B2V) $$example ; \
```

I get this error:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.InternalError: Module jdk.compiler not in boot Layer
	at java.base/sun.launcher.LauncherHelper.loadModuleMainClass(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

I checked my JDK version and it sems to be correctly installed to be 11, as mentioned in the requirements.

```
gokul@~/LLVM-for-MPC/Benchmark$ which java
/usr/bin/java
gokul@~/LLVM-for-MPC/Benchmark$ java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit Compressed References 20210120_910 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
gokul@~/LLVM-for-MPC/Benchmark$ javac --version
javac 11.0.10
```

Here are some more details:

```
gokul@:~/LLVM-for-MPC/Benchmark$ whereis java
java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1
gokul@:~/LLVM-for-MPC/Benchmark$ ls -l /usr/bin/java
lrwxrwxrwx 1 root root 22 Mar  6  2020 /usr/bin/java -> /etc/alternatives/java
gokul@:~/LLVM-for-MPC/Benchmark$ ls -l /etc/alternatives/java
lrwxrwxrwx 1 root root 54 Mar  6  2020 /etc/alternatives/java -> /usr/lib/jvm/adoptopenjdk-11-openj9-jre-amd64/bin/java
```

I am running this on Ubuntu.

```
gokul@:~/LLVM-for-MPC/Benchmark$ uname -a
Linux 5.4.0-71-generic #79~18.04.1-Ubuntu SMP Thu Mar 25 05:45:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cwb38** [comment]
Unfortunately, I cannot reproduce your error on Ubuntu 21.04. Potentially, it is related to using the Eclipse OpenJ9 / AdoptOpenJDK instead of the regular OpenJDK binaries installed when running `apt install openjdk-11-jdk` and updating Java alternatives accordingly.

**Comment by goxul** [comment]
Thank you, that helped! I had to point my JDK to a different version for it to work. In case someone comes here in the future, it now points to:

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```
